### Exercice 1:

Write a function that takes a string, and two indexes (integers), and returns a slice of that string as well as the length of the string.
Call the function, and store the results in two variables

In [1]:
def slice(string,a,b):
    return string[a:b+1]
slice('ismail',0,3)

'isma'

### Exercice 2:

1. Write a function that takes two arguments, and returns the sum of the two.
2. Call the function with the values 1 and 2.1, then check the type of the result.
3. Call the function with the values False and 2, then check the type of the result.

In [2]:
def addition(a, b):
    return a + b
addition(1,2)
addition(False,2)

2

### Exercice 3:

Write a function that takes a string and returns a dictionary containing character frequency.

*example*

    string sample: 'test'
    
    expected result: {'t':2, 'e':1, 's':1}

In [3]:
def CharFreq(string):
    freq = {}
    for i in string:
        if i in freq:
            freq[i] += 1
        else:
            freq[i] = 1
    return freq
CharFreq('ismmail')

{'i': 2, 's': 1, 'm': 2, 'a': 1, 'l': 1}

### Exercice 4:

Given two lists, iterate both lists simultaniously, such the first list would display item in original order and the second list in reverse order

*example*:

In [3]:
from lib import print_orl #this is a lib you dont have access to
print_orl([1,2,3],[1,2,3])

1 3
2 2
3 1


In [4]:
def print_orl(t,l):
    n=len(t)
    for i in range (n):
        print(t[i],l[n-1-i])
print_orl([1,2,3],[3,2,1])

1 1
2 2
3 3


### Exercice 5:

Given two 2d arrays, stack them horizontally.

*example:*

In [3]:
import numpy as np

#The input
a = np.ones((1, 10)).reshape(2, -1)
b = np.zeros((1, 10)).reshape(2, -1)

#Try to print input
#concatenate horizontally
def concat(t,l):
    r=[np.concatenate((t,l),axis=1)]
    return r
#output shoul look like:     array([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
#                                   [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.]])


concat(a,b)



[array([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.]])]

### exercice 6:

Create the following patterns using the bellow arrays a and b, and numpy functions:

In [8]:
a = np.arange(3)
b = np.ones((3,3,3))


#output1 the following array: array([0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2])
import numpy as np
a = np.arange(3)
b = np.ones((3,3,3))
c=0
L = np.empty(9)
for i in range(len(a)):
    for j in range(len(a)):
        L[c]=a[i]
        c+=1
T=np.concatenate((L, a), axis=0)
while i<4:
    T=np.concatenate((T, a), axis=0)
    i=i+1
print(T)

#output2 the follwing array: array([[[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]],

#                                    [[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]],

#                                    [[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]]])
print((a+1)*b)

#output3 array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
#                [1., 1., 1., 1., 1., 1., 1., 1., 1.],
#                [1., 1., 1., 1., 1., 1., 1., 1., 1.]])



[0. 0. 0. 1. 1. 1. 2. 2. 2. 0. 1. 2. 0. 1. 2. 0. 1. 2.]
[[[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]

 [[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]

 [[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]]


[[[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]

 [[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]

 [[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]]
